### ISSUE TITLE
Issue trying to generate a virtual testcard

### ISSUE THREAD

**Issue by NVercauteren** [Fedict/eid-test-cards#6]

**Comment by NVercauteren** [comment]
Trying to generate a virtual card throws an outofbounds exception.

Windows command line : 
..\eid-test-cards-master\gen_virtual_cards\gen_virtual_cards>java -cp "lib/*";src GenVirtual OrigBEIDNVercauteren.eid base.txt out.xml
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -12
        at java.lang.String.substring(Unknown Source)
        at GenVirtual.parseXml(GenVirtual.java:146)
        at GenVirtual.parsePhyicalInfo(GenVirtual.java:88)
        at GenVirtual.generate(GenVirtual.java:52)
        at GenVirtual.main(GenVirtual.java:42)
